import { BoundaryNote, ButtonLink, PageFrame, PageHero, Section } from "../../components/ResearchComponents.js";

const slc = "https://github.com/iwtbotiwtwot/substrate-ledger-computer";

export const dynamic = "force-static";

export const metadata = { title: "Stewardship", description: "The outward-facing custody, share-forward licensing, and public stewardship direction of SAM and SLC.", alternates: { canonical: "/stewardship" } };

export default function StewardshipPage() {
  const principles = ["Widen human agency.","Widen access to useful knowledge and capability.","Preserve origin and contribution accurately.","Preserve failures and corrections.","Keep improvements inspectable and share-forward.","Resist enclosure and extraction.","Do not increase coercive, deceptive, or exploitative power.","Leave a reconstructible path for the next steward."];
  return <PageFrame><PageHero eyebrow="Public custody direction" title={<>Build outward, <em>not upward.</em></>} intro="SAM's public release is not only a publication decision. It is a custody decision: capable people should be able to reconstruct, test, extend, and use the work while carrying its benefit outward." compact /><Section eyebrow="01 · Stewardship principles" title="Capability should widen agency and access." tone="dark"><ol className="sam-principles">{principles.map((principle,index) => <li key={principle}><span>{String(index+1).padStart(2,"0")}</span><strong>{principle}</strong></li>)}</ol></Section><Section eyebrow="02 · Controlling terms" title="Share-forward code, documents, diagrams, and data." intro="The standalone SLC release uses GNU AGPLv3 or later for executable code and CC BY-SA 4.0 for original documents, diagrams, and data. The SAM Stewardship Covenant supplies the outward-facing custody statement."><div className="sam-actions"><ButtonLink href={`${slc}/blob/main/LICENSE.md`} external>Read license policy</ButtonLink><ButtonLink href={`${slc}/blob/main/LICENSES/AGPL-3.0-or-later.txt`} tone="secondary" external>AGPL-3.0-or-later</ButtonLink><ButtonLink href={`${slc}/blob/main/LICENSES/CC-BY-SA-4.0.txt`} tone="secondary" external>CC BY-SA 4.0</ButtonLink><ButtonLink href={`${slc}/blob/main/STEWARDSHIP.md`} tone="ghost" external>Stewardship covenant</ButtonLink></div><BoundaryNote title="Controlling text">This page is a public orientation. The actual files in each repository control its licensing; a summary never replaces those terms.</BoundaryNote></Section></PageFrame>;
}
