import { ButtonLink, PageFrame, PageHero, Section } from "../../components/ResearchComponents.js";

export const dynamic = "force-static";

export const metadata = { title: "About", description: "Authorship, technical collaboration, mission, and public identity of the SAM Research Project.", alternates: { canonical: "/about" } };

export default function AboutPage() {
  return <PageFrame><PageHero eyebrow="Independent public working research" title={<>A human-originated project, <em>built in technical collaboration.</em></>} intro="The SAM Research Project is a public working-research system connecting substrate, matter, and exact computation. SAM is not an OpenAI product." compact /><Section eyebrow="Authorship and contribution" title="Origin and collaboration remain visible." tone="dark"><div className="sam-people"><article><span>Originator and conceptual director</span><h3>Sean Brady</h3><p>Sean Brady is the originator and conceptual director of the SAM Research Project. He supplies the conceptual architecture, theory direction, and research questions.</p></article><article><span>Technical research collaborator</span><h3>OpenAI Codex</h3><p>OpenAI Codex is a technical research collaborator contributing exact implementation, mathematical development, campaign design, execution, repository-scale reconstruction, validation tooling, and documentation.</p></article></div></Section><Section eyebrow="Public mission" title="Release a reconstructible research system." intro="The public record includes the conceptual line, exact machinery, executed results, meaningful failures, corrections, successors, and repository trail needed to inspect how the system developed."><div className="sam-actions"><ButtonLink href="/theory">Read the theory</ButtonLink><ButtonLink href="/research-record" tone="secondary">Inspect the record</ButtonLink><ButtonLink href="/stewardship" tone="ghost">Read stewardship</ButtonLink></div></Section></PageFrame>;
}
